### ISSUE TITLE
Fontbakery output is markdown, not HTML

### ISSUE THREAD

**Issue by davelab6** [googlefonts/Unified-Font-Repository#2]
Currently https://googlefonts.github.io/Unified-Font-Repository/fontbakery-report.html looks like this

<img width="906" alt="Screen Shot 2021-06-07 at 11 33 03" src="https://user-images.githubusercontent.com/261579/121047127-28db4000-c784-11eb-92a1-511b7cad22f4.png">

I guess that is because the github markdown reporter is used, which is intended for github issues/prs, instead of the html reporter. 

I believe that will be a trivial fix to this repo, to change the reporter used on the command line, although I expect this will create new demand for improvements to that direct html report :)

**Comment by simoncozens** [comment]
That *is* using the fontbakery HTML reporter, which these days just processes the markdown inside fontbakery and spits out HTMLified MD.

**Comment by davelab6** [comment]
Ha! OK well here's my demand for improvements to that direct html report :)
