### ISSUE TITLE
Separate the fork

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/Unified-Font-Repository#29]
We won't push back to original repo, so I suggest we separate this one and make it independant

**Comment by simoncozens** [comment]
I agree but I think Dave was keen to acknowledge heritage. @davelab6?

**Comment by RosaWagner** [comment]
It really confuses PRs in github. The original repo is quoted in the README…

**Comment by eliheuer** [comment]
I'm proud of my PRs to this repo, it would be nice to get a contributor badge on the GitHub page for this, which I don't think shows up for forks.

**Comment by RosaWagner** [comment]
@davelab6 approved to make this fork independent 

We could also rename the repo something like "GF Template Repo", since we are not trying to have one repo to rule them all… the "unifying" concept is a dangerous slope imo.

**Comment by simoncozens** [comment]
[GitHub docs](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork) say:
> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support. If the fork has forks of its own, let GitHub Support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."

**Comment by eliheuer** [comment]
This was done, I'm closing this.
