### ISSUE TITLE
Builds are not reproducible

### ISSUE THREAD

**Issue by khaledhosny** [googlefonts/Unified-Font-Repository#34]
Each time `make build` is run the built fonts are marked modified because the `head.modified` timestamp is always set to the time the font is built. This makes it harder to detect when a rebuild actually changes the file.

FontTools respects `SOURCE_DATE_EPOCH` env var when set and uses it for the modification time stamp, I suggest setting (either by default or optionally) to the source file modification time.

**Comment by simoncozens** [comment]
Will do this in the builder. Moving this issue there. Incidentally, that sounds like a useful flag that `fontmake` should also have.
