### ISSUE TITLE
`make test` quits with exit code `2`: `make: *** [build.stamp] Error 245`

### ISSUE THREAD

**Issue by eliheuer** [googlefonts/Unified-Font-Repository#56]
On an M1 Mac, `make test` quits with exit code `2`: `make: *** [build.stamp] Error 245`

I don't see any Fontbakery files in the repo and no Fontbakery output in the terminal.

This is similar to another issue: #57

**Comment by simoncozens** [comment]
You won't be able to `make test` until the files are built, so this is a direct symptom of #57.
