### ISSUE TITLE
FontBakery Badge for GoogleFonts labeled "ERRORED"

### ISSUE THREAD

**Issue by usted** [googlefonts/Unified-Font-Repository#62]
Hi there
Since I've updated my repository to the latest standard, the FontBakery badge for Google Fonts has come out as "ERRORED". 
See: https://github.com/usted/Albert-Sans

It's also says "ERRORED" in the .json file https://github.com/usted/Albert-Sans/blob/gh-pages/badges/GoogleFonts.json

I've tried almost everything. So please let me know what to do?

**Comment by simoncozens** [comment]
The error is in the “can render sample” check. I’ll get that fixed. Meanwhile you can read the whole report at https://github.com/usted/Albert-Sans/blob/gh-pages/fontbakery/fontbakery-report.md

**Comment by usted** [comment]
Thanks for the quick reply and for looking into it :)
I've already been trying to fix all the error and warnings which is possible in the fontbakery-report. But there are a few left which i think is impossible to solve. Where can i post questions on how to solve those?

**Comment by usted** [comment]
Hi @simoncozens i just made a new push but strangely enough it still comes out as errored.
