### ISSUE TITLE
Unified-Font-Repository has stopped producing open-type and variable files

### ISSUE THREAD

**Issue by usted** [googlefonts/Unified-Font-Repository#63]
Since i updated to the new Unified-Font-Repository it has stopped producing open-type and variable files. I now only have the true-type in the proff-folder: https://github.com/usted/Albert-Sans/tree/gh-pages/proof/fonts

Event though there is only TTF in that font-folder i still get the error:
FAIL: Checking all files are in the same directory.
_FAIL Not all fonts passed in the command line are in the same directory. This may lead to bad results as the tool will interpret all font files as belonging to a single font family. The detected directories are: ['fonts/ttf', 'fonts/otf', 'fonts/variable'] [code: single-directory]_
How do it get the otf, and variable produceed again and how do i get fix this error?

**Comment by simoncozens** [comment]
The behaviour is (I think) correct. The proof folder in the gh-pages branch is only designed to hold the HTML proof sheets and the (web)fonts needed to display the proofs. It is not where the final fonts live. To get at the OTF and variable fonts for testing, you can look at the artefact file (see the bottom of https://github.com/usted/Albert-Sans/actions/runs/1405417147); to get at the final fonts for release, create a new release. Or you can just type `make build` in your `Albert-Sans` directory...

However, the fontbakery FAIL is a problem. Maybe we should disable this check for UFR as the fonts *are* going to belong to a single font family. @m4rc1e, WDYT?

**Comment by m4rc1e** [comment]
Hey @usted,

> The behaviour is (I think) correct. The proof folder in the gh-pages branch is only designed to hold the HTML proof sheets and the (web)fonts needed to display the proofs.

Correct.

When I reimplemented the asset generation/packaging, I updated the readme which you may find useful.

> However, the fontbakery FAIL is a problem. Maybe we should disable this check for UFR as the fonts are going to belong to a single font family. @m4rc1e, WDYT?

We should only be checking the fonts in a single directory. For the time being, it's probably best to only check the ttf/ dir. My aim is to one day have a repo config file so the user can specify which dirs to run fb on.

**Comment by usted** [comment]
Hi @simoncozens and @m4rc1e 
Thanks for the help and for fixing it so fast. 
That makes perfectly sense.

Have a great weekend
