### ISSUE TITLE
Current GHAction setup does not install gftools

### ISSUE THREAD

**Issue by felipesanches** [googlefonts/Unified-Font-Repository#9]
...and for that reason, the build fails.

Here's an instance of that problem on the National-Park repo (forked by @benhoepner):
https://github.com/benhoepner/National-Park/runs/2841437066
![Screenshot from 2021-06-16 15-00-24](https://user-images.githubusercontent.com/213676/122269465-9f2e1f80-ceb3-11eb-8083-b4c497b560b7.png)

**Comment by simoncozens** [comment]
Something odd is happening. It does install gftools (see requirements.txt) and if you look back at earlier runs of the National Park repo, it does install the dependencies correctly. Then at run number 6 it stops...

**Comment by simoncozens** [comment]
Looks like the `venv` subdirectory was mistakenly added to the repo, and without the gftools stuff. The correct solution is to add it to `.gitignore` so it doesn't get checked in..
